# circleCI config file for CI/CD

version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0
  terraform: circleci/terraform@1.5.3

workflows:
  deploy_infrastructure:
    jobs:
      - hold:
          type: approval
          requires:
            - plan
      - plan:
          filters:
            branches:
              only: main
          steps:
            - checkout
            - aws-cli/setup
            - terraform/init:
                path: ./terraform
            - terraform/plan:
                path: ./terraform
                workspace: prod
      - apply:
          filters:
            branches:
              only: main  
          steps:
            - checkout
            - aws-cli/setup  
            - terraform/init:
                path: ./terraform
            - terraform/apply:
                path: ./terraform
                workspace: prod