version: 2.1

orbs:
  terraform: circleci/terraform@3.2

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform

      - terraform/validate:
          checkout: true
          context: terraform        
          requires:
            - terraform/fmt

      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true        
          requires:
            - terraform/validate

      - hold:
          type: approval
          requires:
            - terraform/plan

      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - hold
      - hold-destroy:
          type: approval
          requires:
            - terraform/apply
      - terraform/destroy:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - hold-destroy