# circle CI/CD config file
version: 2.1

orbs:
  terraform: circleci/terraform@3.2

workflows:
  deploy:
    # when:
    #  equals: [ << pipeline.git.branch >>, main ]
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          persist-workspace: true
          checkout: true
          context: terraform
          requires:
            - terraform/validate
      - approve_apply:
          type: approval
          requires: 
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          checkout: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - approve_apply
      - approve_destroy:
          type: approval
          requires: 
            - terraform/apply
      - terraform/destroy:
          attach-workspace: true
          checkout: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - approve_destroy